In [1]:
import pandas as pd

# Feed pd.read_csv( ) Method a URL Argument

In [2]:
URL = "https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv"
baby_names = pd.read_csv(URL)

In [3]:
baby_names.head()

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Olivia,172,1
1,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Chloe,112,2
2,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Sophia,104,3
3,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Emily,99,4
4,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Emma,99,4

# Quick Object Conversions

In [4]:
baby_names["Child's First Name"].tolist()

baby_names["Child's First Name"]

0           Olivia
1            Chloe
2           Sophia
3            Emily
4             Emma
5              Mia
6        Charlotte
7            Sarah
8           Hannah
9         Isabella
10           Grace
11          Angela
12             Ava
13          Joanna
14          Amelia
15          Evelyn
16            Arya
17            Ella
18          Ariana
19           Alina
20            Maya
21           Fiona
22          Fatima
23            Anna
24          Ashley
25           Anaya
26            Aria
27         Abigail
28        Victoria
29            Abby
           ...
11315         HUGO
11316        ALLEN
11317      GREYSON
11318       KACPER
11319      CARMINE
11320      SANTINO
11321        SAMIR
11322      STEPHEN
11323       ASHTON
11324      YEHUDAH
11325        BRYCE
11326      NIKOLAS
11327        YONAH
11328        SILAS
11329       SIDNEY
11330        CADEN
11331        ELLIS
11332        DEREK
11333       NOSSON
11334        AYDEN
11335         REED
11336       CALVIN
11337      BENNETT
11338       BERISH
11339     MOHAMMED
11340          LEV
11341     AUGUSTUS
11342        SHAUL
11343       WESLEY
11344      KENNETH
Name: Child's First Name, Length: 11345, dtype: object

In [5]:
#converting series to a dataframe
baby_names["Child's First Name"].to_frame()

      Child's First Name
0                 Olivia
1                  Chloe
2                 Sophia
3                  Emily
4                   Emma
5                    Mia
6              Charlotte
7                  Sarah
8                 Hannah
9               Isabella
10                 Grace
11                Angela
12                   Ava
13                Joanna
14                Amelia
15                Evelyn
16                  Arya
17                  Ella
18                Ariana
19                 Alina
20                  Maya
21                 Fiona
22                Fatima
23                  Anna
24                Ashley
25                 Anaya
26                  Aria
27               Abigail
28              Victoria
29                  Abby
...                  ...
11315               HUGO
11316              ALLEN
11317            GREYSON
11318             KACPER
11319            CARMINE
11320            SANTINO
11321              SAMIR
11322            STEPHEN
11323             ASHTON
11324            YEHUDAH
11325              BRYCE
11326            NIKOLAS
11327              YONAH
11328              SILAS
11329             SIDNEY
11330              CADEN
11331              ELLIS
11332              DEREK
11333             NOSSON
11334              AYDEN
11335               REED
11336             CALVIN
11337            BENNETT
11338             BERISH
11339           MOHAMMED
11340                LEV
11341           AUGUSTUS
11342              SHAUL
11343             WESLEY
11344            KENNETH

[11345 rows x 1 columns]

In [6]:
#to extract a string of all the names in the Child first name column
#name is the temporary variable that I will be assigning to the Child first name column
#using the join method to perform a particular operation 

#what this operation does is that for every name in baby_names DF , use str() to check whether they are
#strings and if yes then join with a ,
", ".join(str(name) for name in baby_names["Child's First Name"])

"Olivia, Chloe, Sophia, Emily, Emma, Mia, Charlotte, Sarah, Hannah, Isabella, Grace, Angela, Ava, Joanna, Amelia, Evelyn, Arya, Ella, Ariana, Alina, Maya, Fiona, Fatima, Anna, Ashley, Anaya, Aria, Abigail, Victoria, Abby, Zoe, Claire, Ayesha, Vivian, Jessica, Audrey, Zoey, Sophie, Zainab, Alice, Rachel, Phoebe, Bella, Amy, Annie, Eva, Kayla, Zara, Maryam, Aisha, Angelina, Ellie, Tiffany, Avery, Riley, Katherine, Natalie, Jasmine, Alexandra, Aleena, Cynthia, Hailey, Elena, Madison, Michelle, Melody, Chelsea, Ivy, Elizabeth, Kaylee, Allison, Queenie, Tenzin, Aizah, Sofia, Leah, Irene, Isabelle, Myra, Stephanie, Ariel, Harper, Inaaya, Alyssa, Christina, Katie, Lily, Nina, Joyce, Iris, Nicole, Cindy, Alisha, Crystal, Mila, Kaitlyn, Manha, Hoorain, Queena, Catherine, Kelly, Amanda, Sara, Arianna, Amber, Hanna, Athena, Jocelyn, Penelope, Serena, Hana, Ayat, Julia, Lydia, Samantha, Elaine, Leanna, Emilia, Clara, Inaya, Jacqueline, Vicky, Mina, Winnie, Sharon, Angel, Amaya, Haniya, Lucy, Elsa, Valerie, Celine, Meera, Karen, Annabelle, Stella, Amara, Eleanor, Carina, Jessie, Joy, Savannah, Anne, Selina, Luna, Esther, Hareem, Taylor, Noor, Miranda, Zahra, Mahnoor, Kira, Scarlett, Bonnie, Sylvia, Layla, Yuna, Eunice, Jenny, Lillian, Amina, Nora, Anjali, Laura, Brianna, Mariam, Mira, Summer, Jannatul, Arisha, Aliyah, Keira, Anabia, Aileen, Lia, Amira, Caroline, Leela, Syeda, Livia, Hazel, Ava, Madison, Skylar, Riley, Aaliyah, Savannah, Chloe, Olivia, Fatoumata, Abigail, Peyton, Zoe, Isabella, Faith, London, Autumn, Sophia, Brielle, Malia, Amelia, Taylor, Mia, Fatima, Arianna, Kayla, Nevaeh, Kylie, Nia, Zoey, Serenity, Aisha, Gabrielle, Aria, Leah, Naomi, Khloe, Laila, Makayla, Mariam, Victoria, Zuri, Mariama, Paige, Grace, Nyla, Morgan, Jasmine, Aminata, Lauren, Emily, Miracle, Hailey, Ariah, Sarah, Layla, Amiyah, Nylah, Emma, Amina, Elizabeth, Heaven, Bella, Chelsea, Ariana, Genesis, Amaya, Ariel, Trinity, Paris, Jordyn, Talia, Kennedy, Gabriella, Imani, Mariah, Kimora, Dakota, Kaylee, Sydney, Alyssa, Destiny, Maya, Jayla, Leilani, Michelle, Charlotte, Aliyah, Aniyah, Lyric, Avery, Aubrey, Tori, Egypt, Arielle, Eliana, Mya, Kiara, Hannah, Isabelle, Journee, Harmony, Janelle, Anaya, Skyla, Maliyah, Zariah, Brianna, Amira, Alani, Jade, Sage, Nala, Nova, Kali, Amirah, Sarai, Londyn, Zara, McKenzie, Brooke, Christina, Gianna, Mackenzie, Alexis, Addison, Danielle, Eva, Joy, Janiyah, Journey, Bintou, Milani, Jada, Sasha, Marley, Tianna, Amara, Eden, Ella, Cali, Oumou, Harper, Mckenzie, Rylee, Aissatou, Aicha, Reign, Nalani, Tamia, Melanie, Malaysia, Audrey, Princess, Kaliyah, Skye, Mikayla, Fanta, Saniyah, Maimouna, Violet, Milan, Tiana, Annabelle, Sanaa, Ashley, Sanai, Zahra, Mila, Kori, Leila, Hope, Jaliyah, Khadija, Blessing, Isabella, Sophia, Mia, Emma, Camila, Sofia, Emily, Valentina, Abigail, Leah, Victoria, Madison, Ava, Olivia, Ashley, Allison, Scarlett, Genesis, Melanie, Brianna, Alexa, Zoe, Hailey, Kimberly, Samantha, Chloe, Ariana, Arianna, Penelope, Amelia, Alaia, Kaylee, Valerie, Maria, Gabriella, Luna, Elizabeth, Layla, Aaliyah, Zoey, Gianna, Amy, Daniela, Nicole, Juliette, Sarah, Charlotte, Mila, Jade, Kylie, Katherine, Bella, Riley, Grace, Gabriela, Kayla, Andrea, Ana, Alyssa, Aubrey, Avery, Maya, Adriana, Amaya, Evelyn, Kiara, Natalia, Aria, Savannah, Khloe, Alice, Valeria, Emely, Serenity, Melissa, Isabel, Leslie, Natalie, Elena, Amber, Diana, Stephanie, Angelina, Skylar, Ximena, Emilia, Michelle, Keyla, Naomi, Mya, Eliana, Ella, Chelsea, Jazlyn, Mariana, Kaitlyn, Aylin, Eva, Sarai, Alana, Delilah, Sara, Aliyah, Alina, Lia, Amanda, Jayleen, Jasmine, Ruby, Alison, Vanessa, Alexandra, Violet, Jocelyn, Amaia, Antonella, Leilani, Brittany, Angelica, Juliet, Sophie, Liliana, Melany, Juliana, Maia, Danna, London, Briana, Audrey, Athena, Jayla, Autumn, Jessica, Sherlyn, Selena, Rose, Julianna, Lauren, Amalia, Aurora, Nova, Destiny, Jennifer, Jazmin, Alondra, Daniella, Stella, Helen, Julia, April, Annabelle, Bianca, Miranda, Giselle, Arya, Lily, Angie, Mariah, Jaylene, Madelyn, Catalina, Sabrina, Samara, Lucia, Alejandra, Keily, Laila, Yaretzi, Esther, Karen, Guadalupe, Daisy, Alessandra, Liana, Heaven, Valery, Sasha, Nathalia, Ariella, Esmeralda, Isabelle, Izabella, Natasha, Kelly, Eileen, Analia, Kamila, Itzel, Alicia, Jacqueline, Leila, Sienna, Hannah, Brielle, Carla, Annalise, Skyla, Cataleya, Jaylah, Nashla, Mackenzie, Angela, Allyson, Aileen, Leia, Nathaly, Bryanna, Aleah, Luciana, Camilla, Lizbeth, Megan, Rachel, Nyla, Amirah, Anastasia, Sadie, Nylah, Mikaela, Elianna, Elisa, Erika, Gia, Celine, Hazel, Miah, Laura, Kendra, Arabella, Evangeline, Josephine, Jamie, Angelique, Britney, Kaylie, Skyler, Faith, Makayla, Fatima, Alia, Ruth, Alani, Ayleen, Lesly, Melody, Eliza, Khaleesi, Tiffany, Jaelyn, Roselyn, Aliah, Paige, Malia, Nathalie, Luz, Yamileth, Madeline, Montserrat, Lillian, Alaina, Harley, Leilany, Anaya, Rosemary, Kelsey, Nia, Elianny, Arlette, Scarlet, Adelyn, Arianny, Celeste, Dayana, Arielle, Amayah, Fernanda, Alexis, Alanna, Jaylin, Zara, Anna, Jasmin, Kaylani, Wendy, Paris, Jolie, Crystal, Veronica, Noemi, Belen, Cassandra, Amina, Shirley, Peyton, Jimena, Karla, Janelle, Caroline, Trinity, Adeline, Ivanna, Kate, Alayna, Nayeli, Isabela, Olivia, Rachel, Esther, Sarah, Emma, Charlotte, Chaya, Leah, Ava, Chana, Miriam, Sara, Sophia, Maya, Emily, Rivka, Mia, Elizabeth, Ella, Sofia, Alexandra, Amelia, Malka, Faigy, Malky, Gitty, Grace, Abigail, Isabella, Zoe, Anna, Lily, Madison, Victoria, Hannah, Gabriella, Julia, Chloe, Alice, Eva, Stella, Harper, Emilia, Mila, Sophie, Penelope, Sienna, Rivky, Yitty, Layla, Violet, Evelyn, Avery, Raizy, Baila, Riley, Valentina, Toby, Naomi, Eleanor, Rose, Claire, Madeline, Caroline, Maria, Shaindy, Talia, Ruby, Devorah, Nora, Chany, Lila, Josephine, Fiona, Lucy, Rebecca, Natalie, Amina, Samantha, Sloane, Sadie, Scarlett, Eliana, Gianna, Clara, Liliana, Dina, Isabelle, Juliette, Chava, Yocheved, Pearl, Angelina, Nina, Ariana, Katherine, Lillian, Audrey, Noa, Alexa, Aria, Nicole, Hazel, Blima, Vivienne, Isla, Juliet, Isabel, Libby, Esty, Lucia, Elle, Adele, Molly, Adeline, Hailey, Nechama, Kayla, Vivian, Frances, Michelle, Anastasia, Quinn, Goldy, Rochel, Maeve, Juliana, Willa, Shoshana, Francesca, Gemma, Fraidy, Annabelle, Margaret, Addison, Sury, Cora, Madelyn, Lyla, Sydney, Giuliana, Natalia, Savannah, Jane, June, Hindy, Yides, Mira, Ariella, Emerson, Mackenzie, Eloise, Bella, Leila, Diana, Bracha, Lara, Mary, Eliza, Elena, Ellie, Mariam, Laila, Pessy, Daniella, Faiga, Ahuva, Alexis, Kira, Luna, Mindy, Alessia, Blimy, Skylar, Samira, Ada, Keira, Maryam, Margot, Phoebe, Noor, Georgia, Yael, Sasha, Alessandra, Dylan, Madeleine, Ayla, Shira, Summer, Arielle, Lydia, Adina, Sabrina, Milana, Catherine, Liana, Perl, Alina, Amalia, Brooke, Raizel, Charlie, Zoey, Beatrice, Avigail, Gabriela, Salma, Alma, Gittel, Taylor, Cecilia, Bianca, Colette, Ruchy, Hana, Camilla, Lola, Aurora, Alyssa, Lea, Helen, Elise, Adriana, Olive, Ivy, Julianna, Ruth, Iris, Eve, Celine, Chavy, Lana, Louise, Matilda, Hanna, Reese, Arianna, Idy, Tzipora, Shaina, Sylvie, Genevieve, Lena, Frady, Veronica, Hadassah, Yehudis, Bruchy, Frimet, Aliza, Fradel, Willow, Amelie, Devora, Layan, Kate, Malika, Annabel, Elisheva, Morgan, Henny, Sabina, Raquel, Vera, Shifra, Siena, Zissy, Serena, Malak, Adelaide, Golda, Brianna, Rifka, Tziporah, Blake, Paige, Louisa, Nadia, Rivkah, Brucha, Liv, Esme, Perel, Reagan, Livia, Mirel, Judy, Brielle, Eden, Freida, Amy, Teagan, Etty, Dahlia, Gabrielle, Shea, Gia, Tova, Lia, Vienna, Frieda, Ryan, Simone, Lauren, Rifky, Juniper, Batsheva, Antonia, Tessa, Elisa, Julie, Liora, Toba, Laura, Shevy, Aubrey, Jacqueline, Edith, Basya, Amanda, Hadley, Hinda, Fatima, Batya, Adrianna, Freya, Liba, Trany, Lilah, Everly, Camille, Maia, Miri, Breindy, Jenna, Madina, Harley, Anne, Kaia, Farida, Dalia, Sima, Tamar, Goldie, Lilly, Zara, Diyora, Valerie, Leyla, Alisa, Camila, Daria, Aviva, Cleo, Katerina, Poppy, Danielle, Christina, Marlowe, Michal, Delilah, Vanessa, Finley, Tamara, Brynn, Ana, Maggie, Lina, Yasmin, Ashley, Brooklyn, Suri, Autumn, Sonia, Zelda, Nicolette, Margaux, Reem, Briella, Evangeline, Riva, Lilliana, Zainab, Sylvia, Logan, Ethan, Ryan, Muhammad, Lucas, Jayden, Aiden, Daniel, Evan, Jason, Liam, Matthew, Austin, Eric, Kevin, William, Justin, Owen, Mohammad, Oliver, Aaron, Noah, Henry, Benjamin, Mason, Nathan, Alexander, Leo, Vincent, Ian, Dylan, Andrew, Jacob, Kyle, Jonathan, Ivan, James, Michael, Samuel, Brian, Syed, Brandon, Ibrahim, Alex, Abdullah, Alvin, Max, Jasper, Eason, Kai, Tenzin, Logan, Ayaan, Jeremy, Andy, Darren, Gavin, Joshua, Joseph, Mohammed, Adam, Julian, Theodore, Rayan, Marcus, Nicholas, Arham, Jaden, David, Alan, Sean, Raymond, Zachary, Aidan, Anthony, Rohan, Connor, Kyson, Derek, Oscar, Tyler, Luke, Jackson, Ayden, Caleb, Nathaniel, Christopher, Aryan, Isaac, Christian, Tristan, Zayn, Winston, Steven, Adrian, Allen, Arjun, Hudson, Wesley, Sebastian, Louis, Hamza, Yusuf, George, Xavier, Rayyan, Elijah, Jordan, Anson, Kingsley, Miles, Jerry, Harrison, Gabriel, Caden, Benson, Jack, Ayan, Charles, Kayden, Thomas, Musa, Bryan, John, Felix, Lawrence, Roy, Eli, Aarav, Preston, Jeffrey, Carson, Ahnaf, Leon, Zayan, Aayan, Richard, Chris, Md, Abdul, Ahmed, Mustafa, Hunter, Krish, Kabir, Edison, Calvin, Hashim, Aaryan, Cameron, Rehan, Azaan, Maxwell, Armaan, Brayden, Johnny, Cyrus, Adyan, Kian, Elvis, Ahmad, Carter, Eden, Damon, Stanley, Ashton, Aden, Shawn, Aydin, Jace, Cody, Albert, Edward, Asher, Hayden, Simon, Aahil, Lincoln, Hugo, Farhan, Edwin, Terry, Ali, Victor, Nelson, Grayson, Robert, Cayden, Ryder, Timothy, Alston, Mikael, Wilson, Sulaiman, Devin, Kimi, Noah, Aiden, Elijah, Liam, Ethan, Jeremiah, Amir, Joshua, Josiah, Mason, Carter, Jayden, Michael, David, Logan, Chase, King, Christian, Cameron, Tyler, Isaiah, Jacob, Malachi, Zion, Daniel, Kayden, Messiah, Ayden, Kaiden, Mohamed, Samuel, Christopher, Kyrie, Ryan, Jayce, Justin, Caleb, Nathan, Xavier, Aaron, Tristan, Jace, Amari, Nathaniel, Matthew, Jaden, Prince, Ashton, Joel, Jonathan, Hunter, Anthony, Alexander, Jason, Dylan, Jordan, Jayceon, Brandon, Gabriel, Bryson, Adonis, Nasir, Bryce, Emmanuel, Kyle, Karter, Zachary, Avery, Mamadou, Austin, Kai, Lucas, Omari, Micah, Ibrahim, Chance, Sebastian, Joseph, Nicholas, James, Maison, Kaleb, Eli, Adam, Andrew, Isaac, Ezra, Malik, Benjamin, Julian, Major, Jaiden, Richard, William, Robert, Royal, John, Nolan, Elias, Adrian, Legend, Zaire, Kevin, Alpha, Jaxon, Grayson, Justice, Levi, Mekhi, Ousmane, Princeton, Andre, Giovanni, Muhammad, Sean, Khalil, Maximus, Asher, Kaden, Jaylen, Shane, Mouhamed, Ezekiel, Alex, Aidan, Darius, Ibrahima, Kameron, Jamari, Jonas, Sincere, Timothy, Jaxson, Judah, Israel, Victor, Amadou, Preston, Bryan, Peyton, Greyson, Cairo, Charles, Kamari, Blake, Caiden, Marcus, George, Kingston, Derrick, Nehemiah, Jonah, Abdoul, Moussa, Connor, Ameer, Miles, Ali, Camren, Wyatt, Abraham, Oumar, Zayden, Damari, Henry, Brayden, Cayden, Myles, Omar, Kyree, Jamal, Liam, Jacob, Dylan, Matthew, Noah, Sebastian, Ethan, Jayden, Lucas, Aiden, Daniel, Angel, Alexander, Mason, Christopher, Aaron, Mateo, Joshua, Adrian, Anthony, David, Michael, Gabriel, Logan, Isaac, Ian, Joseph, Ryan, Julian, Josiah, Justin, Jose, Kevin, Elijah, Luis, Jonathan, Benjamin, James, Samuel, Nathan, Jeremiah, John, Jeremy, Carlos, Nicholas, Christian, Andrew, Ayden, Brandon, Xavier, Elias, Leonardo, Diego, Erick, Axel, Jesus, Oliver, Alan, Kayden, Emmanuel, Steven, Gael, Thiago, Joel, Santiago, Jason, Alex, Alejandro, Nicolas, William, Damian, Austin, Adam, Juan, Jace, Isaiah, Bryan, Jayce, Nathaniel, Matteo, Abraham, Jordan, Evan, Miguel, Johan, Derek, Abel, Iker, Jake, Hunter, Adriel, Edward, Leo, Ivan, Caleb, Javier, Oscar, Alexis, Eli, Jadiel, Josue, Henry, Matias, Messiah, Edwin, Tyler, Brayden, Victor, Bradley, Jackson, Andy, Mathias, King, Zachary, Elian, Jonah, Rafael, Cristian, Dominic, Jaxon, Giovanni, Jaden, Julius, Emanuel, Jorge, Max, Jayson, Thomas, Andres, Pablo, Cameron, Kenneth, Owen, Jack, Carter, Emilio, Allen, Robert, Lorenzo, Maximiliano, Brian, Julio, Hector, Noel, Chase, Jaiden, Eric, Greyson, Peter, Aidan, Vincent, Francisco, Avery, Eduardo, Ismael, Richard, Anderson, Cesar, Jonas, Bryce, Kaiden, Dariel, Amir, Ezra, Jefferson, George, Manuel, Jaxson, Zion, Zayden, Moises, Damien, Prince, Grayson, Tristan, Leandro, Levi, Nolan, Mathew, Uriel, Ricardo, Maison, Mark, Bryson, Luke, Joaquin, Chris, Ean, Milan, Dominick, Maximus, Marcos, Israel, Luca, Jeffrey, Martin, Pedro, Jaycob, Ariel, Jay, Charles, Adonis, Abdiel, Angelo, Lukas, Kenny, Andre, Roman, Enzo, Edgar, Marcus, Louis, Brayan, Kai, Maxwell, Isaias, Kaden, Roberto, Yadiel, Raymond, Kyrie, Ezekiel, Valentino, Jean, Landon, Marco, Sergio, Franklin, Fernando, Randy, Armani, Eliel, Harrison, Jariel, Mario, Adiel, Jael, Jimmy, Frank, Enrique, Kyle, Byron, Johann, Kaleb, Rodrigo, Felipe, Omar, Alessandro, August, Hudson, Ezequiel, Lenny, Zabdiel, Jax, Elliot, Jared, Leonidas, Miles, Paul, Allan, Timothy, Johnny, Kelvin, Jasiah, Nathanael, Arturo, Fabian, Eliam, Kendrick, Sean, Marlon, Gavin, Antonio, Nelson, Edison, Lionel, Mike, Matthias, Maximilian, Jayceon, Felix, Albert, Caiden, Darwin, Dante, Asher, Joseph, Michael, David, Moshe, Jacob, James, Benjamin, Alexander, Daniel, Henry, Jack, Adam, William, Abraham, Samuel, Noah, John, Isaac, Oliver, Chaim, Nicholas, Ethan, Ryan, Liam, Matthew, Gabriel, Leo, Eli, Theodore, Lucas, Yosef, Thomas, Charles, Andrew, Dylan, Anthony, Shimon, Max, Yisroel, Luke, Mordechai, Yehuda, Menachem, Luca, Julian, Sebastian, Zachary, Jackson, George, Mason, Owen, Christopher, Jonathan, Asher, Robert, Nathan, Yitzchok, Shlomo, Aiden, Omar, Hudson, Joshua, Miles, Mark, Aron, Maxwell, Shmuel, Nathaniel, Connor, Yakov, Logan, Meir, Levi, Aaron, Ezra, Shaya, Ali, Dov, Simon, Tzvi, Ari, Oscar, Edward, Adrian, Vincent, Jonah, Hunter, Avraham, Harrison, Zev, Solomon, Yaakov, Christian, Eliezer, Peter, Leon, Leonardo, Jake, Wyatt, Evan, Aidan, Cole, Dovid, Moses, Sam, Mendel, Grayson, Nolan, Mohamed, Patrick, Judah, Gavin, Finn, Dean, Arthur, Israel, Shulem, Ahmed, Elijah, Elias, Nicolas, Elliot, Raphael, Paul, Chase, Shmiel, Aryeh, Colin, Rocco, Antonio, Lipa, Simcha, Amir, Ben, Frank, Wesley, Cooper, Kai, Tyler, Eliyahu, Yechiel, Hershy, Roman, Matteo, Mayer, Philip, Lukas, Rayan, Lazer, Luka, Richard, Parker, Milo, Rafael, Alan, Naftuli, Naftali, Yousef, Alex, Graham, Charlie, Declan, Jude, August, Giovanni, Theo, Yusuf, Elliott, Hamza, Justin, Jordan, Carter, Emmett, Jason, Hershel, Quinn, Austin, Ariel, Cameron, Victor, Conor, Maximilian, Shia, Maxim, Marco, Martin, Maximus, Felix, Lorenzo, Ian, Timothy, Lev, Grant, Rowan, Louis, Spencer, Landon, Sean, Caleb, Avrohom, Brandon, Yehoshua, Ellis, Reid, Noam, Youssef, Dominic, Akiva, Usher, Eitan, Marcus, Shlome, Meshilem, Cheskel, Eric, Arlo, Gavriel, Baruch, Albert, Shloime, Abdullah, Mendy, Ibrahim, Bennett, Avi, Shloimy, Everett, Jaxon, Salvatore, Jasper, Nico, Jayden, Elimelech, Morris, Hugo, Efraim, Kyle, Aharon, Kevin, Samir, Hersh, Muhammad, Yossi, Shane, Brian, Joel, Francesco, Angelo, Mateo, Pinchas, Anas, Mohammed, Moishe, Bodhi, Ryder, Benzion, Binyamin, Calvin, Donovan, Blake, Axel, Damian, Chesky, Zalmen, Raymond, Ronan, Vincenzo, Harry, Silas, Pinchus, Avery, Yoel, Reuven, Timur, Yisrael, Leonard, Mohammad, Frederick, Beckett, Brody, Griffin, Pierce, Jace, Elya, Tristan, Francis, Greyson, Steven, Jaxson, Boruch, Micah, Xavier, Jad, Yitzchak, Malik, Dominick, Brayden, Stephen, River, Avrum, Julien, Giuseppe, Brendan, Sholom, Cyrus, Jay, Ameer, Otto, Yonatan, Enzo, Lucian, Fishel, Zayn, Ayden, Sami, Desmond, Imran, Ivan, Selim, Yassin, Milan, Motty, Shalom, Gregory, Jesse, Ahmad, Peretz, Shraga, Zain, Walter, Santino, Josef, Marcel, Nikolai, Ahron, Russell, Wolf, Jeremy, Isaiah, Gianluca, Bradley, Eyad, Lincoln, Dillon, Noach, Leonidas, Mordche, Winston, Joaquin, Berl, Elan, Nosson, Malek, Meilech, Augustus, Camden, Meyer, Leibish, Colton, Umar, Aviel, Nikolas, Walker, Herman, Olivia, Chloe, Sophia, Emily, Emma, Grace, Isabella, Mia, Angela, Charlotte, Amelia, Ava, Anaya, Claire, Hannah, Sarah, Evelyn, Bella, Zoe, Jessica, Kayla, Ella, Fatima, Abigail, Leah, Rachel, Jasmine, Alice, Avery, Vivian, Hailey, Angelina, Maya, Joanna, Sophie, Anna, Fiona, Victoria, Elena, Aria, Ashley, Alina, Audrey, Stella, Kaylee, Arya, Ariana, Ellie, Madison, Sofia, Tenzin, Catherine, Elizabeth, Annie, Abby, Ayesha, Serena, Lily, Zainab, Tiffany, Iris, Stephanie, Zara, Michelle, Cindy, Melody, Amy, Phoebe, Sara, Naomi, Manha, Zahra, Natalie, Kaitlyn, Vicky, Penelope, Lillian, Christina, Ivy, Maryam, Allison, Aisha, Queenie, Nicole, Selina, Mila, Eva, Katherine, Jenny, Kelly, Cynthia, Julia, Alisha, Hanna, Rebecca, Arianna, Irene, Nina, Amber, Shirley, Aleena, Sabrina, Elina, Isabelle, Anika, Harper, Zoey, Emilia, Elsa, Jannat, Nabiha, Leela, Mariam, Celine, Ruby, Lucy, Eileen, Queena, Caroline, Arisha, Amanda, Jocelyn, Angel, Samaira, Aiza, Janice, Winnie, Alexandra, Katie, Luna, Elaine, Inaaya, Jessie, Alexis, Madeline, Joyce, Savannah, Sienna, Kira, Lydia, Jennifer, Tanisha, Annabelle, Lauren, Lena, Joy, Eliana, Mira, Aarya, Jannatul, Eleanor, Elise, Diana, Raina, Sylvia, Aizah, Erica, Maliha, Hafsa, Haniya, Giselle, Cecilia, Emaan, Alyssa, Karina, Priscilla, Ariel, Anabia, Megan, Christine, Isla, Riley, Josephine, Isabel, Tina, Clara, Lisa, Scarlett, Khloe, Layla, Samantha, Noor, Anisa, Skylar, Karen, Mahnoor, Jacqueline, Madison, Skylar, Ava, Olivia, Mia, Taylor, Chloe, Aaliyah, Savannah, Kylie, London, Riley, Leah, Serenity, Kayla, Peyton, Zoe, Nyla, Brielle, Autumn, Gabriella, Faith, Makayla, Zoey, Abigail, Arianna, Layla, Aria, Zuri, Khloe, Emily, Gabrielle, Amelia, Sarah, Nevaeh, Aminata, Aisha, Nia, Morgan, Fatima, Mariam, Victoria, Ariel, Fatoumata, Kennedy, Isabelle, Aubrey, Naomi, Sophia, Alyssa, Sarai, Hailey, Amiyah, Elizabeth, Amina, Nylah, Leilani, Laila, Lauren, Paige, Maya, Jada, Isabella, Kali, McKenzie, Arielle, Kaylee, Grace, Ariana, Malia, Brianna, Trinity, Sydney, Londyn, Harmony, Avery, Zara, Jade, Michelle, Milan, Jordyn, Amirah, Heaven, Mya, Esther, Mariama, Amaya, Mariah, Chelsea, Skyla, Kyla, Jasmine, Jayla, Destiny, Maliyah, Lyric, Eva, Malaysia, Journey, Janiyah, Emma, Bintou, Amira, Tori, Alana, Imani, Aniyah, Genesis, Kimora, Bella, Aliyah, Paris, Hawa, Nova, Skye, Miracle, Summer, Mikayla, Samara, Gianna, Skyler, Egypt, Hannah, Sanai, Melanie, Charlotte, Dakota, Aissatou, Christina, Zendaya, Leila, Ariah, Nala, Amara, Sanaa, Wynter, Kelsey, Ashley, Zahra, Cali, Marley, Kadiatou, Milani, Kaliyah, Amia, Aicha, Mackenzie, Fatou, Oumou, Alani, Danielle, Kaitlyn, Kailee, Erin, Taliyah, Sariah, Zahara, Lauryn, Samiyah, Samantha, Ariella, Brooke, Zariah, Jordan, Alexandria, Sky, Eden, Brooklyn, Amber, Tiana, Athena, Shiloh, Joy, Jayda, Saige, Lily, Royal, Julia, Angel, Janiya, Mila, Anaya, Sariyah, Isabella, Sophia, Mia, Emma, Camila, Sofia, Abigail, Ashley, Emily, Madison, Victoria, Alexa, Leah, Valentina, Scarlett, Olivia, Brianna, Ariana, Samantha, Allison, Kimberly, Genesis, Hailey, Melanie, Zoe, Amy, Ava, Elizabeth, Chloe, Arianna, Kaylee, Alaia, Kylie, Amelia, Sarah, Aaliyah, Gabriella, Daniela, Delilah, Emely, Savannah, Gabriela, Bella, Nicole, Penelope, Valerie, Adriana, Layla, Zoey, Jade, Andrea, Katherine, Mila, Luna, Maya, Isabel, Aubrey, Maria, Eva, Juliette, Michelle, Grace, Charlotte, Amaya, Avery, Eliana, Alina, Evelyn, Diana, Skylar, Kayla, Angelina, Khloe, Ana, Valeria, Riley, Aylin, Melany, Jayleen, Stephanie, Chelsea, Kiara, Amanda, Leslie, Serenity, Leilani, Jazmin, Vanessa, Gianna, Naomi, Natalie, Alyssa, Lucia, Athena, Kaitlyn, Amber, Sarai, Mya, Jasmine, Juliet, Lia, Danna, Elena, Madelyn, Ella, Aurora, Violet, Hannah, Briana, Brittany, Maia, Yaretzi, Alexandra, Sophie, Melissa, Alana, Jennifer, Karen, Lizbeth, Alison, Ximena, Sara, Natalia, Kamila, Jaylene, Juliana, Angelica, Liliana, Aria, N

# Export CSV File with the .to_csv( ) Method

In [7]:
baby_names.to_csv("NYC Baby Names.csv", index = False, columns = ["Year of Birth","Child's First Name","Count"], encoding = "utf-8")
#exported the csv to current working directory i.e. where we are working in the pandas folder on desktop
#utf-8 includes all the characters of modern languages . if any encoding issues =, always use this param

# Import Excel File

In [9]:
df = pd.read_excel("Data - Single Worksheet.xlsx")
df

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [12]:
pd.read_excel("Data - Multiple Worksheets.xlsx", sheet_name = "Data 2")
#pandas will export the first tab in line of the worksheet and others will be ignored
#sheetname parameter requires us to provide either name of the worksheet or the numeric position

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [13]:
pd.read_excel("Data - Multiple Worksheets.xlsx", sheet_name = ["Data 1", "Data 2"])

OrderedDict([('Data 1',   First Name Last Name           City Gender
              0    Brandon     James          Miami      M
              1       Sean   Hawkins         Denver      M
              2       Judy       Day    Los Angeles      F
              3     Ashley      Ruiz  San Francisco      F
              4  Stephanie     Gomez       Portland      F),
             ('Data 2',   First Name Last Name           City Gender
              0     Parker     Power        Raleigh      F
              1    Preston  Prescott   Philadelphia      F
              2    Ronaldo   Donaldo         Bangor      M
              3      Megan   Stiller  San Francisco      M
              4     Bustin    Jieber         Austin      F)])

In [15]:
data = pd.read_excel("Data - Multiple Worksheets.xlsx", sheet_name = [0,1])

In [16]:
type (data)

collections.OrderedDict

In [19]:
data[1]

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [22]:
data1 = pd.read_excel("Data - Multiple Worksheets.xlsx", sheet_name = None)
#sheetname = None is the quickest way to ensure all the tabs get bundled and have 
#names like Data1 , Data 2 ETC

In [21]:
data1

OrderedDict([('Data 1',   First Name Last Name           City Gender
              0    Brandon     James          Miami      M
              1       Sean   Hawkins         Denver      M
              2       Judy       Day    Los Angeles      F
              3     Ashley      Ruiz  San Francisco      F
              4  Stephanie     Gomez       Portland      F),
             ('Data 2',   First Name Last Name           City Gender
              0     Parker     Power        Raleigh      F
              1    Preston  Prescott   Philadelphia      F
              2    Ronaldo   Donaldo         Bangor      M
              3      Megan   Stiller  San Francisco      M
              4     Bustin    Jieber         Austin      F)])

# Export Excel File

In [29]:
URL = "https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv"
baby_names = pd.read_csv(URL)
baby_names.head(3)

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Olivia,172,1
1,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Chloe,112,2
2,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,Sophia,104,3

In [30]:
girls = baby_names[baby_names["Gender"] == "FEMALE"]
boys = baby_names[baby_names["Gender"] == "MALE"]

In [32]:
excel_file = pd.ExcelWriter("Baby Names.xlsx")

In [36]:
girls.to_excel(excel_file, sheet_name = "Girls", index = False)
boys.to_excel(excel_file, sheet_name = "Boys", index = False, columns = ["Gender", "Child's First Name", "Count"])

In [37]:
excel_file.save()